version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import sys,urllib.request; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/api/v1/health/health', timeout=3).status==200 else sys.exit(1)\""]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}

  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile
    volumes:
      - ./cli:/app
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    driver: bridge
